version: "3"
services:
  web:
    build: .
    container_name: flask_template
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./log:/code/log:rw
    depends_on:
      - mongo
  mongo:
    image: mongo
    container_name: mongo_for_flask_template
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin_user
      MONGO_INITDB_ROOT_PASSWORD: admin_password
      MONGO_INITDB_DATABASE: admin
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    volumes:
      - ./mongodbdata:/data/db
